name: Azure App Service CI/CD (adminspheree)
 
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
<<<<<<< HEAD
          node-version: '20.19.0'   # change if you use a different version
=======
          node-version: '18'
>>>>>>> 63e036d93fece261a85b36c228185ebc4ad5ede6
 
      - name: Install dependencies
        run: npm ci
 
      - name: Build frontend and backend
        run: npm run build
 
      - name: Deploy to Azure App Service (adminspheree)
        uses: azure/webapps-deploy@v2
        with:
          app-name: "adminspheree"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .